temporary fix the alpine package issue
ERROR: unable to select packages:
  ncurses-terminfo-base-6.4_p20240420-r0:
    breaks: libpanelw-6.4_p20240420-r1[ncurses-terminfo-base=6.4_p20240420-r1]
    satisfies: libncursesw-6.4_p20240420-r0[ncurses-terminfo-base=6.4_p20240420-r0]